version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front_end_c
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back_end_c
    ports:
      - "4000:4000"
    networks:
      - my-network
