version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front_end_c
    ports:
      - "5173:5173"
    networks:
      - my-network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back_end_c
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=alpha_trades

  db:
    build:
      context: ./back-end/database
      dockerfile: Dockerfile
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alpha_trades
      TZ: "Europe/Athens"
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - ./back-end/database/data:/var/lib/mysql
      - ./back-end/database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
