# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Sets the working directory
WORKDIR /usr/src/app

# Copy the package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application files
COPY . .

# Build the application
RUN yarn build

# Expose port 4000
EXPOSE 4000

# Run the application
CMD ["yarn", "start"]
